/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nepal.lms.ui.book.returnn;

import com.nepal.lms.action.ReturnListener;
import com.nepal.lms.bll.ReturnBLL;
import com.nepal.lms.custom.Alert;
import com.nepal.lms.entity.returnn.Return;
import com.nepal.lms.entity.user.UserInfo;
import com.nepal.lms.exception.CorruptedDataException;
import com.nepal.lms.exception.MissingFileException;
import com.nepal.lms.exception.RecordNotFoundException;
import com.nepal.lms.ui.BaseUserPanel;
import com.nepal.lms.util.Logy;
import com.nepal.lms.util.Utils;
import com.nepal.lms.view.BookView;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @returnn Suzn
 */
public final class BookReturnPanel extends BaseUserPanel implements BookView<Return>, ReturnListener {

    private List<Return> returnnList;
    private final UserInfo userInfo;

    private ReturnListener returnnListener;

    /**
     * Creates new form BookReturnPanel
     *
     * @param userInfo
     */
    public BookReturnPanel(UserInfo userInfo) {
        initComponents();
        this.userInfo = userInfo;
        setupUserView(userInfo);
        returnnList = new ArrayList<>();
        this.loadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        centerSubPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        bottomPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        addBookReturnButton = new javax.swing.JButton();
        updateBookReturnButton = new javax.swing.JButton();
        deleteBookReturnButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        centerPanel.setLayout(new java.awt.CardLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        searchPanel.setBackground(new java.awt.Color(249, 249, 249));
        searchPanel.setPreferredSize(new java.awt.Dimension(367, 70));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        searchPanel.setLayout(flowLayout1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(280, 65));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_blue.png"))); // NOI18N

        searchTextField.setBackground(new java.awt.Color(249, 249, 249));
        searchTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchTextField.setToolTipText("Search for title, publisher, author..");
        searchTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(39, 26, 252)));
        searchTextField.setMinimumSize(new java.awt.Dimension(200, 15));
        searchTextField.setOpaque(false);
        searchTextField.setPreferredSize(new java.awt.Dimension(200, 15));
        searchTextField.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                String text = searchTextField.getText();
                System.out.println(text);
                if (text.trim().length() == 0) {
                    ((javax.swing.table.TableRowSorter<javax.swing.table.TableModel>)table.getRowSorter()).setRowFilter(null);
                } else {
                    ((javax.swing.table.TableRowSorter<javax.swing.table.TableModel>)table.getRowSorter()).setRowFilter(javax.swing.RowFilter.regexFilter("^(?i)" + text));
                }
                table.repaint();
            }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                String text = searchTextField.getText();
                if (text.trim().length() == 0) {
                    ((javax.swing.table.TableRowSorter<javax.swing.table.TableModel>)table.getRowSorter()).setRowFilter(null);
                } else {
                    ((javax.swing.table.TableRowSorter<javax.swing.table.TableModel>)table.getRowSorter()).setRowFilter(javax.swing.RowFilter.regexFilter("^(?i)" + text));
                }
            }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                //not needed: throw new UnsupportedOperationException("Not supported yet.");
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(searchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        searchPanel.add(jPanel2);

        jPanel4.add(searchPanel, java.awt.BorderLayout.PAGE_START);

        centerSubPanel.setLayout(new java.awt.CardLayout());

        javax.swing.table.DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel(){
            @Override
            public boolean isCellEditable(int i, int i1) {
                return false;
            }
        };

        tableModel.addColumn(com.nepal.lms.entity.returnn.ReturnParams.ID.toUpperCase());
        tableModel.addColumn(com.nepal.lms.entity.returnn.ReturnParams.BOOK.toUpperCase());
        tableModel.addColumn(com.nepal.lms.entity.returnn.ReturnParams.MEMBER.toUpperCase());
        tableModel.addColumn(com.nepal.lms.entity.returnn.ReturnParams.USER.toUpperCase());
        tableModel.addColumn(com.nepal.lms.entity.returnn.ReturnParams.RETURNED_DATE.toUpperCase());
        table.setModel(tableModel);
        table.setRowHeight(26);
        table.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(table);
        javax.swing.table.TableRowSorter<javax.swing.table.TableModel> rowSorter = new javax.swing.table.TableRowSorter<>(table.getModel());
        table.setRowSorter(rowSorter);

        centerSubPanel.add(jScrollPane1, "card2");

        jPanel4.add(centerSubPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        jPanel3.setOpaque(false);

        addBookReturnButton.setText("Add New");
        addBookReturnButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addBookReturnButton.setPreferredSize(new java.awt.Dimension(80, 40));
        addBookReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookReturnButtonActionPerformed(evt);
            }
        });
        jPanel3.add(addBookReturnButton);

        updateBookReturnButton.setText("Update");
        updateBookReturnButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateBookReturnButton.setPreferredSize(new java.awt.Dimension(80, 40));
        updateBookReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBookReturnButtonActionPerformed(evt);
            }
        });
        updateBookReturnButton.setVisible(false);
        jPanel3.add(updateBookReturnButton);

        deleteBookReturnButton.setText("Delete");
        deleteBookReturnButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteBookReturnButton.setPreferredSize(new java.awt.Dimension(80, 40));
        deleteBookReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookReturnButtonActionPerformed(evt);
            }
        });
        jPanel3.add(deleteBookReturnButton);

        bottomPanel.add(jPanel3);

        jPanel4.add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        centerPanel.add(jPanel4, "card2");

        add(centerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addBookReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookReturnButtonActionPerformed
        BookReturnInsertDialog bookReturnInsertDialog = new BookReturnInsertDialog((JFrame) SwingUtilities.getWindowAncestor(this), true, userInfo);
        bookReturnInsertDialog.setItemAddedListener((Return returnn) -> {
            appendReturnData(returnn);
        });
        bookReturnInsertDialog.setVisible(true);
    }//GEN-LAST:event_addBookReturnButtonActionPerformed

    private void updateBookReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBookReturnButtonActionPerformed
        int row = table.getSelectedRow();
        if (row > -1) {
            Return s = getBeanFromRow(row);
            if (s != null) {
                BookReturnUpdateDialog bookReturnUpdateDialog = new BookReturnUpdateDialog((JFrame) SwingUtilities.getWindowAncestor(this),
                        true, s);
                bookReturnUpdateDialog.setItemUpdatedListener((Return returnn) -> {
                    updateReturnData(returnn, row);
                });
                bookReturnUpdateDialog.setVisible(true);
            }
        }
    }//GEN-LAST:event_updateBookReturnButtonActionPerformed

    private void deleteBookReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookReturnButtonActionPerformed
        if (Utils.isTableRowSelected(table)) {
            if (Alert.showDeleteConfirmDialog(this) == JOptionPane.YES_OPTION) {
                int row = table.getSelectedRow();
                int id = Utils.getIdFromTable(table, row);
                try {
                    Return retn = new Return();
                    retn.setId(id);
                    ReturnBLL.deleteReturn(retn);
                    removeReturnData(retn, row);
                } catch (RecordNotFoundException | MissingFileException | CorruptedDataException ex) {
                    Logy.e(ex);
                    Alert.showError(this, ex.getMessage());
                }
            }

        }
    }//GEN-LAST:event_deleteBookReturnButtonActionPerformed

    @Override
    public final void loadTableData() {

        if (returnnList == null || returnnList.isEmpty()) {
            Logy.d("Loading returnn from file for first Time");
            try {
                returnnList = ReturnBLL.getAllReturn();
            } catch (RecordNotFoundException | MissingFileException | CorruptedDataException ex) {
                Logy.e(ex);
                Alert.showError(this, ex.getMessage());
                return;
            }

        } else {
            Logy.d("returnn already loaded");
        }

        this.fillTableData(returnnList);

    }

    /**
     *
     * @param returnnInfoList
     */
    @Override
    public final void fillTableData(List<Return> returnnInfoList) {

        returnnInfoList.stream().forEach((returnnInfo) -> {
            addReturnRowData(returnnInfo);
        });

    }

    public void addReturnRowData(Return returnn) {
        ((DefaultTableModel) table.getModel()).insertRow(0, new Object[]{
            returnn.getId(),
            returnn.getBook().getTitle(),
            returnn.getMember().getName(),
            returnn.getUser().getName(),
            Utils.millisToSql(returnn.getReturnedDate())
        });
    }

    private void updateReturnData(Return s, int row) {
        for (Return returnn : returnnList) {
            if (returnn.getId() == returnn.getId()) {
                returnn.setBook(returnn.getBook());
                returnn.setMember(returnn.getMember());
                break;
            }
        }

        updateReturnRowData(s, row);
//        if (returnnListener != null) {
//            returnnListener.onReturnDataChanged(s);
//        }
    }

    private void updateReturnRowData(Return returnn, int row) {
        ((DefaultTableModel) table.getModel()).setValueAt(returnn.getBook().getTitle(), row, 1);
        ((DefaultTableModel) table.getModel()).setValueAt(returnn.getMember().getName(), row, 2);
        ((DefaultTableModel) table.getModel()).setValueAt(Utils.millisToSql(returnn.getReturnedDate()), row, 4);
    }

    private Return getBeanFromRow(int row) {
        int id = (int) table.getModel().getValueAt(row, 0);
        return returnnList.stream()
                .filter((returnn) -> returnn.getId() == id)
                .findFirst()
                .orElse(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookReturnButton;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel centerSubPanel;
    private javax.swing.JButton deleteBookReturnButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JTable table;
    private javax.swing.JButton updateBookReturnButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onReturnDataChanged(Return a) {
        appendReturnData(a);
    }

    private void appendReturnData(Return returnn) {
        returnnList.add(returnn);
        addReturnRowData(returnn);
        if (returnnListener != null) {
            returnnListener.onReturnDataChanged(returnn);
        }
    }

    @Override
    protected void setupAdminView() {
    }

    @Override
    protected void setupLibrarianView() {
        this.deleteBookReturnButton.setVisible(false);
    }

    /**
     * @return the returnnListener
     */
    public ReturnListener getReturnListener() {
        return returnnListener;
    }

    /**
     * @param returnnListener the returnnListener to set
     */
    public void setReturnListener(ReturnListener returnnListener) {
        this.returnnListener = returnnListener;
    }

    @Override
    public void onReturnDataRemoved(Return r) {
        for (Return auth : returnnList) {
            if (auth.getId() == r.getId()) {
                returnnList.remove(auth);
                break;
            }
        }

    }

    private void removeReturnData(Return a, int row) {
        onReturnDataRemoved(a);
        ((DefaultTableModel) table.getModel()).removeRow(row);
    }
}
